# Generated by Django 3.2.4 on 2021-06-24 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
